blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:pk>', views.blog_detail, name='blog_detail')
    ]

portfolio/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from django.views.generic.base import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('blog/', include('blog.urls'))
]

projects/urls.py
from django.urls import path
from projects import views

app_name = 'projects'

urlpatterns = [
    path('', views.all_projects, name='all_projects'),
    path('<int:pk>', views.project_detail, name='project_detail')
    ]

blog/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    date_created = models.DateTimeField(default=datetime.now())
    image = models.ImageField(upload_to='static/blog')


class BlogComment(models.Model):
    created_by = models.CharField(max_length=100, verbose_name="Name")
    created_email = models.EmailField(max_length=255, verbose_name="Email")
    content = models.CharField(max_length=1000)
    post_date = models.DateTimeField(default=datetime.now())
    blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)

projects/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    stack = models.CharField(max_length=50)
    image = models.CharField(max_length=100)
    video_link = models.CharField(max_length=100)
    github_link = models.URLField()

blog/forms.py
from django.forms import ModelForm
from blog.models import BlogComment

class BlogSubmitForm(ModelForm):
    class Meta:
        model = BlogComment
        fields = ['content', 'created_by', 'created_email',]

blog/views.py
from django.shortcuts import render
from blog.models import BlogPost, BlogComment
from blog.forms import BlogSubmitForm
# Create your views here.

def all_blogs(request):

    blogs = BlogPost.objects.all()
    return render(request, 'blog/all_blogs.html',
                  {'blogs': blogs})

def blog_detail(request, pk):
    blogpost = BlogPost.objects.get(pk=pk)
    comments = BlogComment.objects.filter(blog_post=blogpost)
    print(comments)

    if request.method == 'POST':
        form = BlogSubmitForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.blog_post = blogpost
            new_comment.save()
    else:
        form = BlogSubmitForm()

    return render(request, 'blog/blog_detail.html', {'blogpost': blogpost,
                                                     'form': form,
                                                     'comments': comments})

projects/views.py
import git

from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse

from projects.models import Project


# Create your views here.

# project views
def all_projects(request):
    # query DB and return all project objects
    projects = Project.objects.all()
    return render(request, 'projects/all_projects.html',
                  {'projects': projects})

def project_detail(request, pk):
    project = Project.objects.get(pk=pk)

    return render(request, 'projects/project_detail.html',
                  {'project':project})

@csrf_exempt
def update_server(request):
    if request.method == 'POST':
        repo = git.Repo('https://www.pythonanywhere.com/user/jtatecc27/files/home/jtatecc27/MyPortfolio')
        origin = repo.remotes.origin

        origin.pull()
        return HttpResponse('Python Anywhere Code Updated')
    else:
        return HttpResponse('Code Not Updated')

blog/templates/blog/all_blogs.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Development Blog{% endblock title %}

{% block page-header %}Development Blog{% endblock page-header %}

{% block content %}

    <div class="blog-content">
        <h1>Development Blog</h1>
        <div class="blog-grid-container">
            {% for b in blogs %}
            <div class="blog-card">
                <div class="blog-title-all">
                    <a href="{% url 'blog:blog_detail' b.pk %}"><h3 class="blog-title"> {{ b.title }} </h3></a>
                </div>
                <div class="blog-date-all">
                    <p class="blog-date"> {{ b.date_created }} </p>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
{% endblock content %}

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %} {{ blogpost.title }} {% endblock title %}

{% block page-header %} {{ blogpost.title }} {% endblock page-header %}

{% block content %}

<div class="blog-detail-content">
    <div class="blog-detail-grid">

            <div class="blog-header-info">
            <h2> {{ blogpost.title }} </h2>
            <p> {{ blogpost.date_created }} </p>
            </div>

            <div class="spacer horizontal g1"></div>

            <div class="blog-detail-info">
                <div class="blog-image">
                    <img src="{% static blogpost.image %}">
                </div>
                <div class="blog-text-content">
                    {{ blogpost.content }}
                </div>
            </div>


        <div class="spacer vertical grid-item g2"></div>

        <div class="comment-form grid-item">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class=btn type="submit">Submit Comment</button>
            </form>
        </div>

        <div class="spacer horizontal grid-item g3"></div>

        <div class="comment-container grid-item">
            <h3>Comments</h3>
            {% for c in comments %}
            <div class="comment-section">
                <div class="comment-content">
                    <p>{{ c.content }}</p>
                </div>
                <div class="comment-info">
                    <p>{{ c.created_by }}</p>
                    <p>{{ c.post_date }}</p>
                </div>
            </div>
            <div class="spacer horizontal"></div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

projects/templates/projects/all_projects.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="project-content">
    <h1>Projects</h1>
    <div class="row">
    {% for project in projects %}
        <div class="project-card">
            <img class="project-image" src="{% static project.image %}" alt="{{ project.title }}">
            <h3>{{ project.title }}</h3>
            <a class="project-link" href="{% url 'projects:project_detail' pk=project.id %}">View Details</a>
        </div>


    {% endfor %}
    </div>
</div>

{% endblock %}

projects/templates/projects/detail.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}

    <h1>{{ project.title }}</h1>
    <div class="row">
        <div class="col-md-8">
            <img src="{% static project.image %}" alt="{{ project.description }}" width="100%">
        </div>
        <div class="col-md-4">
            <h5>About the project</h5>
            <p>{{ project.description }}</p>
            <h5>Built with:</h5>
            <p>{{ project.stack }}</p>
            <h5>GitHub:</h5>
            <p>
                <a href="{{ project.github_link }}">Link to Repo</a>
            </p>

        </div>
    </div>

{% endblock %}

projects/templates/projects/project_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <div class="project-detail-content">
        <h1>{{ project.title }}</h1>
        <div class="spacer horizontal"></div>
        <div class=project-info>
            <div class="project-about">
                <h5>About the project</h5>
                <p>{{ project.description }}</p>
            </div>

            <div class="spacer vertical"></div>

            <div class="project-video">
                <iframe width="420" height="315"
                src="{{ project.video_link }}">
                </iframe>
            </div>

            <div class="spacer vertical"></div>

            <div class="project-details">
            <h5>Built with:</h5>
                <p>{{ project.stack }}</p>
                <h5>GitHub:</h5>
                <p><a href="{{ project.github_link }}">Link to Repo</a></p>
            </div>
        </div>
    </div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=max-width, initial-scale=1.0">
        <meta name="description" content="{% block meta_description %}{% endblock %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <title>{% block title %}Base Title{% endblock title %}</title>
    </head>
    <body>
        <div class="top-level">
            <div class="main-container">
                <header>
                    <div class="navigation">
                        <nav class="navbar navbar-expand-lg navbar-dark">
                            <a class="navbar-brand" href="#"><img src="{% static 'img/5NNCD8-LogoMakr.png' %}" height="50px" opacity="0"></a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarNav">
                                <ul class="navbar-nav">
                                    <li class="nav-item active">
                                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'projects:all_projects' %}">Projects</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
                                    </li>
                                </ul>

                            </div>

                        </nav>
                    </div>
                    <!-- Social Icons and Email -->
                    <div class="social-icons">
                        <a href="mailto:jtate.cc@outlook.com" target="_blank"><i class="fa fa-envelope"></i></a>
                        <a href="https://www.linkedin.com/in/jack-tate-codes/" target="_blank"><i class="fa fa-linkedin"></i></a>
                        <a href="https://twitter.com/jack_tate_codes" target="_blank"><i class="fa fa-twitter"></i></a>
                        <a href="https://github.com/JTateCC" target="_blank"><i class="fa fa-github"></i></a>
                    </div>

                </header>

                <div class="spacer horizontal"></div>


                <div class="block-content">
                    {% block content %}

                    {% endblock content %}

                </div>

            </div>

        </div>

    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Jack Tate - Full Stack Developer {% endblock title %}

{% block meta_description %}Home Page for Jack Tate Portfolio{% endblock %}


{% block content %}


        <div class="main-content">
            <div class="overview-container">
                <div class="overview-message">
                    <h1>Jack Tate</h1>
                    <h3> Full Stack Developer</h3>
                </div>
                <div class="spacer horizontal"></div>
                <div class="about-message">
                    <span>
                    <p>A Full Stack Developer based in West Midlands, UK. I have developed a range
                        of applications from Backend PDM systems and Inventory Management through to interactive Job Management Systems.</p>
                    <p> My primary interests lie in building powerful back-end systems and leveraging the potential of Python, Javascript and other Tech for a wide range of applications.
                        I believe in the importance of clean code, scalability, and continuously learning and adapting to the ever-evolving technology landscape.</p>
                    <p> I developed this site as a personal portfolio to showcase my projects and to share my development journey via my blog. Let's collaborate and make great code.</p>
                    </span>
                </div>
            </div>
            <div class="spacer vertical"></div>
            <div class="button-container">
                <span><a id=project-btn class="btn" href="{% url 'projects:all_projects' %}">Projects</a></span>
                <span><a id=blog-btn class="btn" href="{% url 'blog:all_blogs' %}">Blog</a></span>
            </div>
        </div>





{% endblock content %}